export const AIRCLASS_SERVER_VIDEOS = {
  // Valuación de aeronaves 1era parte
  AIRCRAFT_VALUATION_1_1: 'cursos/valuacion_de_aeronaves/1_1_introduccion.mp4',
  AIRCRAFT_VALUATION_1_2: 'cursos/valuacion_de_aeronaves/1_2_biografia_ponente.mp4',
  AIRCRAFT_VALUATION_1_3: 'cursos/valuacion_de_aeronaves/1_3_introduccion_covbaero.mp4',
  AIRCRAFT_VALUATION_1_4: 'cursos/valuacion_de_aeronaves/1_4_presentacion_participantes_1.mp4',
  AIRCRAFT_VALUATION_1_5: 'cursos/valuacion_de_aeronaves/1_5_presentacion_participantes_2.mp4',
  AIRCRAFT_VALUATION_1_6: 'cursos/valuacion_de_aeronaves/1_6_hitos_aviacion.mp4',
  AIRCRAFT_VALUATION_1_7: 'cursos/valuacion_de_aeronaves/1_7_legislacion_aeronautica.mp4',
  // Valuación de aeronaves 2da parte
  AIRCRAFT_VALUATION_2_1: 'cursos/valuacion_de_aeronaves/2_1_participantes_relevantes.mp4',
  AIRCRAFT_VALUATION_2_2: 'cursos/valuacion_de_aeronaves/2_2_clasificacion_aeronaves.mp4',
  AIRCRAFT_VALUATION_2_3: 'cursos/valuacion_de_aeronaves/2_3_partes_aeronaves.mp4',
  AIRCRAFT_VALUATION_2_4: 'cursos/valuacion_de_aeronaves/2_4_superficies_control_primarias.mp4',
  AIRCRAFT_VALUATION_2_5: 'cursos/valuacion_de_aeronaves/2_5_superficies_control_secundarias.mp4',
  AIRCRAFT_VALUATION_2_6: 'cursos/valuacion_de_aeronaves/2_6_zonas_aeronaves.mp4',
  AIRCRAFT_VALUATION_2_7: 'cursos/valuacion_de_aeronaves/2_7_inspeccion_walk_around.mp4',
  // Valuación de aeronaves 3ra parte
  AIRCRAFT_VALUATION_3_1: 'cursos/valuacion_de_aeronaves/3_1_tipos_motores_reciproco.mp4',
  AIRCRAFT_VALUATION_3_2: 'cursos/valuacion_de_aeronaves/3_2_tipos_motores_turbinas.mp4',
  AIRCRAFT_VALUATION_3_3: 'cursos/valuacion_de_aeronaves/3_3_mantenimiento_programado.mp4',
  AIRCRAFT_VALUATION_3_4: 'cursos/valuacion_de_aeronaves/3_4_mantenimiento_no_programado.mp4',
  AIRCRAFT_VALUATION_3_5: 'cursos/valuacion_de_aeronaves/3_5_conceptos_valor.mp4',
  AIRCRAFT_VALUATION_3_6: 'cursos/valuacion_de_aeronaves/3_6_enfoques_valuacion.mp4',
  AIRCRAFT_VALUATION_3_7: 'cursos/valuacion_de_aeronaves/3_7_valor_reposicion.mp4',
  AIRCRAFT_VALUATION_3_8: 'cursos/valuacion_de_aeronaves/3_8_conceptos_depreciacion.mp4',
  AIRCRAFT_VALUATION_3_9: 'cursos/valuacion_de_aeronaves/3_9_metodos_calculo_depreciacion.mp4',
  // Valuación de aeronaves 4ta parte
  AIRCRAFT_VALUATION_4_1: 'cursos/valuacion_de_aeronaves/4_1_presentacion_ejercicios.mp4',
  AIRCRAFT_VALUATION_4_2: 'cursos/valuacion_de_aeronaves/4_2_primera_parte_ejercicio.mp4',
  AIRCRAFT_VALUATION_4_3: 'cursos/valuacion_de_aeronaves/4_3_segunda_parte_ejercicio.mp4',
  AIRCRAFT_VALUATION_4_4: 'cursos/valuacion_de_aeronaves/4_4_tercera_parte_ejercicio.mp4',
  // Valuación de aeronaves 5ta parte
  AIRCRAFT_VALUATION_5_1: 'cursos/valuacion_de_aeronaves/5_1_saludo_registro_asistencia.mp4',
  AIRCRAFT_VALUATION_5_2: 'cursos/valuacion_de_aeronaves/5_2_introduccion_presentacion_primer_caso.mp4',
  AIRCRAFT_VALUATION_5_3: 'cursos/valuacion_de_aeronaves/5_3_primer_caso_1.mp4',
  AIRCRAFT_VALUATION_5_4: 'cursos/valuacion_de_aeronaves/5_4_primer_caso_2.mp4',
  AIRCRAFT_VALUATION_5_5: 'cursos/valuacion_de_aeronaves/5_5_primer_caso_3.mp4',
  AIRCRAFT_VALUATION_5_6: 'cursos/valuacion_de_aeronaves/5_6_primer_caso_4.mp4',
  AIRCRAFT_VALUATION_5_7: 'cursos/valuacion_de_aeronaves/5_7_presentacion_segundo_caso.mp4',
  AIRCRAFT_VALUATION_5_8: 'cursos/valuacion_de_aeronaves/5_8_segundo_caso_1.mp4',
  AIRCRAFT_VALUATION_5_9: 'cursos/valuacion_de_aeronaves/5_9_segundo_caso_2.mp4',
  AIRCRAFT_VALUATION_5_10: 'cursos/valuacion_de_aeronaves/5_10_segundo_caso_3.mp4',
  AIRCRAFT_VALUATION_5_11: 'cursos/valuacion_de_aeronaves/5_11_segundo_caso_4.mp4',
  AIRCRAFT_VALUATION_5_12: 'cursos/valuacion_de_aeronaves/5_12_segundo_caso_5.mp4',
  AIRCRAFT_VALUATION_5_13: 'cursos/valuacion_de_aeronaves/5_13_metodo_multi_criterio.mp4',
  AIRCRAFT_VALUATION_5_14: 'cursos/valuacion_de_aeronaves/5_14_cierre_despedida.mp4',
  // Economía del transporte aéreo
  // INTRODUCCIÓN
  AIR_TRANSPORT_ECONOMY_0_1: 'cursos/economia_del_transporte_aereo/introduction/1_1_introduction_course.mp4',
  // Modulo 1
  AIR_TRANSPORT_ECONOMY_1_1: 'cursos/economia_del_transporte_aereo/modulo_1/1_1_course_map.mp4',
  AIR_TRANSPORT_ECONOMY_1_2: 'cursos/economia_del_transporte_aereo/modulo_1/1_2_module_objectives.mp4',
  AIR_TRANSPORT_ECONOMY_1_3: 'cursos/economia_del_transporte_aereo/modulo_1/1_3_modules_resources.mp4',
  AIR_TRANSPORT_ECONOMY_1_4: 'cursos/economia_del_transporte_aereo/modulo_1/1_4_capacity_regulated_by_gobernments.mp4',
  AIR_TRANSPORT_ECONOMY_1_5: 'cursos/economia_del_transporte_aereo/modulo_1/1_5_principles_behind_capacity_regulation_by_gobernments.mp4',
} as const